# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/example_test.ipynb.

# %% auto 0
__all__ = ['read_csv']

# %% ../nbs/example_test.ipynb 1
import pandas as pd
def read_csv(path, **kwargs):
    """Reads a csv file into a pandas DataFrame.

    Args:
        path (str): Path to the csv file.
        **kwargs: Keyword arguments passed to pandas.read_csv.

    Returns:
        DataFrame: A pandas DataFrame.
    """
    return pd.read_csv(path, **kwargs)
