# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/overview_helper.ipynb.

# %% auto 0
__all__ = ['overview_markdown']

# %% ../nbs/overview_helper.ipynb 1
def overview_markdown(path):
    with open(path, 'r') as f:
        overview = f.read()
    return overview
