# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/valid_update.ipynb.

# %% auto 0
__all__ = ['set_openai_key_default', 'api_key_update']

# %% ../nbs/valid_update.ipynb 1
import os
import json

# %% ../nbs/valid_update.ipynb 2
def set_openai_key_default(key_json_path=""):
    try:
        key_dict = json.load(open(key_json_path, 'r'))
        for key in key_dict:
            os.environ[key] = key_dict[key]
    except:
        print("It is better to create a json file with your OpenAI key and set the path as api_key.json in the root repo folder.")

# %% ../nbs/valid_update.ipynb 3
def api_key_update(choice = "Use my own API key",  key_json_path="", preferece_api_key=None,):
    message = "You choose to "

    if choice == "Use default API key in backend":
        set_openai_key_default(key_json_path)
        message += "use default API key in backend."
    
    else:
        os.environ['OPENAI_API_KEY'] = preferece_api_key
        message += 'use your own API key.'

    return message
